#!/usr/bin/env python

# --- SETUP ---
import os, glob, sys
curr_dir = os.path.dirname(__file__) + '/'
sys.path.append(os.path.join(curr_dir,'tools'))
from fabricate import *
def erlc(infile):
    run('erlc','-smp','-W','-I',curr_dir+'include/','-o',
			curr_dir+'ebin/',curr_dir+'src/'+infile+'.erl')

def erlc_glob(glob_relative_to_src):
    for infile in glob.glob(curr_dir+'src/'+glob_relative_to_src):
        run('erlc','-smp','-W','-I',curr_dir+'include/','-o',curr_dir+'ebin/',
				infile)


# --- ACTUAL BUILD SCRIPT ---
run('mkdir','-p',curr_dir+'include')
run('mkdir','-p',curr_dir+'ebin')

erlc('zml')
erlc('zml_hand_parser')
erlc('zml_tokenizer')
erlc_glob('../src-specials/zml_special*.erl')
