#!/usr/bin/env python

# --- SETUP ---
import os, glob, sys
curr_dir = os.path.dirname(__file__) + '/'
sys.path.append(os.path.join(curr_dir,'tools'))
from fabricate import *
from fabricate import default_builder

if len(sys.argv) > 1 and sys.argv[1] == '-q':
    default_builder.quiet = True

default_builder.depsname = curr_dir + '.deps'

def erlc(infile):
    run('erlc','-smp','-W','-I',curr_dir+'include/','-o',
			curr_dir+'ebin/',curr_dir+'src/'+infile+'.erl')

def erlc_glob(glob_relative_to_src):
    for infile in glob.glob(curr_dir+'src/'+glob_relative_to_src):
        run('erlc','-smp','-W','-I',curr_dir+'include/','-o',curr_dir+'ebin/',
				infile)


# --- ACTUAL BUILD SCRIPT ---
run('mkdir','-p',curr_dir+'include')
run('mkdir','-p',curr_dir+'ebin')

erlc('zml')
erlc('zml_indent')
erlc('zml_tag')
erlc('zml_render')
erlc_glob('../src-specials/zml_special*.erl')
erlc_glob('../src-specials/zs_*.erl')

erlc('zss')
erlc('zss_tokenizer')
erlc('zss_parser')

erlc('zss_tests')

