-module(out_scratch).
-export([test/0, render/1]).

test() ->
  render([
    {data, [[1,2,3],[4,5,6],[7,8,9]]}
    ]).
render(D) ->
["<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n",
 ["<","html",
  [" ","encoding","=\"","utf-8","\""," ","onload","=\"","dosomestuff();","\"",
   " ","stylesheets","=\"","screen samp3","\""],
  ">",
  [["<","head",[],">",
    [["<","title",[],">",
      [["<","strong",
        [" ","class","=\"","awesome","\""],
        ">",
        ["Great"],
        "</","strong",">"],
       "stuff"," ","here"],
      "</","title",">"]],
    "</","head",">"],
   ["<","one",
    [" ","class","=\"","game fast fun","\""," ","id","=\"","home","\""],
    "/>"],
   ["<","div",
    [" ","class","=\"","there","\""," ","id","=\"","two hey","\""],
    "/>"],
   ["<","div",
    [" ","class","=\"","three going","\""," ","id","=\"","howsit","\""],
    "/>"],
   ["<","head",[],">",
    [["<","title",[],">",
      [["<","strong",
        [" ","class","=\"","awesome","\""],
        ">",
        ["Great"],
        "</","strong",">"],
       "stuff"," ","here"],
      "</","title",">"]],
    "</","head",">"],
   ["<","body",[],">",
    [["<","div",
      [" ","id","=\"","home","\""],
      ">",
      ["And"," ","Some text that will be here",
       ["<","br",[" ","id","=\"","how","\""],"/>"],
       ["<","div",
        [" ","id","=\"","wrapper","\""],
        ">",
        [["<","table",[],">",
%          [["!!CODE!!","for val1, val2, val3 in data","!!",
%            [["<","tr",[],">",
%              [["<","td",[],">",["{val1}"],"</","td",">"],
%               ["<","td",[],">",["{val2}"],"</","td",">"],
%               ["<","td",[],">",["{val3}"],"</","td",">"]],
%              "</","tr",">"]],
%            "!!END!!"]],
          [[lists:map(fun([Val1,Val2,Val3]) -> 
            [["<","tr",[],">",
              [["<","td",[],">",[io_lib:format("~p",[Val1])],"</","td",">"],
               ["<","td",[],">",[io_lib:format("~p",[Val2])],"</","td",">"],
               ["<","td",[],">",[io_lib:format("~p",[Val3])],"</","td",">"]],
              "</","tr",">"]] end,
          proplists:get_value(data, D))]],
          "</","table",">"],
         ["<","div",
          [" ","class","=\"","title","\""," ","id","=\"","betaTitle","\""],
          ">",
          ["Do"," ","some"," ","great"," ","stuff!"],
          "</","div",">"],
         ["<","div",
          [" ","class","=\"","subtitle","\""],
          ">",
          ["You"," ","decide"," ","what"," ","we're"," ","doing"," ","today!"],
          "</","div",">"],
         ["<","div",
          [" ","class","=\"","logo","\""," ","id","=\"","betaLogo","\""],
          ">",
          [["<","object",
            [" ","width","=\"","156","\""," ","heigh","=\"","100","\""],
            ">",
            [["<","param",
              [" ","value","=\"","images/avatar.swf","\""," ","name","=\"",
               "movie","\""],
              "/>"],
             ["<","param",
              [" ","value","=\"","transparent","\""," ","name","=\"","wmode",
               "\""],
              "/>"],
             ["<","embed",
              [" ","width","=\"","156","\""," ","src","=\"",
               "images/avatar.swf","\""," ","height","=\"","100","\""," ",
               "wmode","=\"","transparent","\""],
              "/>"]],
            "</","object",">"]],
          "</","div",">"],
         ["<","div",[" ","class","=\"","awesomeness","\""],"/>"]],
        "</","div",">"]],
      "</","div",">"]],
    "</","body",">"]],
  "</","html",">"]].

